require(httr)
require(jsonlite)

url = "https://biotools.fr/mouse/ensembl_symbol_converter/"
raw <- scan("./data/rna/ensembl.txt", character())
#raw <- read.csv("./data/rna/ensembl.txt", header=F)
ids_json <- toJSON(raw)
print("Ids loaded")
body <- list(api=1, ids=ids_json)
print("body has been initiated")
r <- POST(url, body = body)
print("POST success")
#output = fromJSON( content(r, "text"), flatten=TRUE)
output = fromJSON( content(r, "text"))
print("Output received from API")
capture.output(output, file = "./data/rna/symbols.txt")
#write.csv(output,file="./data/rna/symbols.txt",row.names=TRUE)
